export const regions = [
  "LA-Sao Paulo1",
  "LA-Santiago",
  "CN-Hong Kong",
  "AP-Bangkok",
  "AP-Singapore",
  "AP-Jakarta",
  "AP-Manila",
  "AF-Johannesburg",
  "AF-Cairo",
  "TR-Istanbul",
  "ME-Riyadh",
  "LA-Mexico City1",
  "LA-Mexico City2",
  "EU-Paris",
  "AP-Kuala Lumpur-OP6",
  "LA-Buenos Aires1",
  "UAE-Abu Dhabi",
  "CN North-Beijing4",
  "CN East-Shanghai1",
  "CN South-Guangzhou",
  "CN Southwest-Guiyang1",
  "CN East-Qingdao",
  "CN East2",
  "EU-Dublin",
  "TR-Ankara-PUR"
];
